version: '3'
services:
  dev:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    volumes:
      - .:/app
      - nuget:/root/.nuget
    tmpfs:
      - /app/bin:exec
      - /app/obj
    entrypoint: dotnet watch --no-hot-reload
    # entrypoint: bash
    ports:
      - 5012:5012
    tty: true
    restart: unless-stopped
    environment:
     # - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - OTLP_GRPC_ENDPOINT=http://host.docker.internal:4317
      - ISSUER_URI=https://lemur-9.cloud-iam.com/auth/realms/bangbaew
      - EXPOSE_EXPERIMENTAL_FEATURES=true

  # dapr:
  #   image: "daprio/daprd:edge"
  #   command: ["./daprd",
  #    "-app-id", "tracking-manager",
  #    "-app-port", "5012",
  #    "-placement-host-address", "host.docker.internal:6050",
  #    "-components-path", "/components"]
  #   volumes:
  #     - "../dapr/components-dev:/components"
  #   depends_on:
  #     - dev
  #   network_mode: "service:dev"
  #   restart: unless-stopped

volumes:
  nuget:
    external: true
